#!/bin/bash

set -e

if gnulib-tool --version >/dev/null 2>&1; then
    echo "Updating gnulib files from $GNULIB_SRCDIR"

    gnulib-tool \
        --import \
        --lib=libgnu \
        --source-base=lib \
        --m4-base=m4 \
        --doc-base=. \
        --tests-base=test \
        --aux-dir=build-aux \
        --no-conditional-dependencies \
        --no-libtool \
        --macro-prefix=gl \
        byteswap \
        configmake \
        dirname \
        dup2 \
        getline \
        getopt-gnu \
        gettext \
        gettimeofday \
        lstat \
        malloc-gnu \
        manywarnings \
        memchr \
        minmax \
        progname \
        stdbool \
        stdint \
        strcase \
        strdup-posix \
        strerror \
        strndup \
        strstr \
        vasprintf \
        version-etc \
        xalloc \
        xalloc-die \
        xvasprintf
else
    echo "***"
    echo "Warning: gnulib is required for initial compilation"
    echo "***"
fi

aclocal -I m4
autoheader
libtoolize --force -c
automake -a -c
autoconf

mkdir build && cd build && ../configure
